all: cube sphere teapot

cube: cube.c
	g++ cube.c -lGL -lGLU -lglut -lm -Iinclude -L. -lIrrKlang -o cube
	
sphere: sphere.c
	g++ sphere.c -lGL -lGLU -lglut -lm -Iinclude -L. -lIrrKlang -o sphere
	
teapot: teapot.c
	g++ teapot.c -lGL -lGLU -lglut -lm -Iinclude -L. -lIrrKlang -o teapot
